# Generated by Django 6.0 on 2025-12-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fileasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='confirmed_by_requester',
            field=models.BooleanField(default=False, help_text='Requester confirms task completion'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('confirmed', 'Confirmed by Requester'), ('commented', 'Commented'), ('deleted', 'Deleted')], max_length=20),
        ),
    ]
