# Generated by Django 6.0 on 2025-12-19 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_collaborators'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='api.ticketcomment'),
        ),
    ]
