# Generated by Django 6.0 on 2025-12-22 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_department_product_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dept_approved_at',
            field=models.DateTimeField(blank=True, help_text='When department manager approved', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dept_approver',
            field=models.ForeignKey(blank=True, help_text='Department manager who gave first approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_approved_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('dept_approved', 'Department Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('confirmed', 'Confirmed by Requester'), ('commented', 'Commented'), ('deleted', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_request', 'New Request'), ('pending_creative', 'Pending Creative Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('comment', 'Comment'), ('deadline', 'Deadline Approaching'), ('idle', 'Task Idle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('pending_creative', 'Pending Creative Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
