# Generated by Django 6.0 on 2025-12-23 03:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_two_step_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='snapshot',
            field=models.JSONField(blank=True, help_text='Ticket state snapshot at this point for rollback functionality', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_by',
            field=models.ForeignKey(blank=True, help_text='User who deleted this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_tickets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('dept_approved', 'Department Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('confirmed', 'Confirmed by Requester'), ('commented', 'Commented'), ('deleted', 'Deleted'), ('rollback', 'Rolled Back')], max_length=20),
        ),
    ]
