# Generated by Django 6.0 on 2025-12-23 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_loginattempt_user_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_rollback_at',
            field=models.DateTimeField(blank=True, help_text='Last time this ticket was rolled back', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rollback_count',
            field=models.IntegerField(default=0, help_text='Number of times this ticket has been rolled back'),
        ),
        migrations.CreateModel(
            name='TicketAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(help_text='When ticket was created')),
                ('dept_approved_at', models.DateTimeField(blank=True, help_text='When dept manager approved', null=True)),
                ('creative_approved_at', models.DateTimeField(blank=True, help_text='When creative approved', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When ticket was assigned', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When work started', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When work completed', null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, help_text='When requester confirmed', null=True)),
                ('last_rollback_at', models.DateTimeField(blank=True, help_text='Last rollback time', null=True)),
                ('rollback_count', models.IntegerField(default=0, help_text='Total rollback count')),
                ('time_to_dept_approval', models.IntegerField(blank=True, help_text='Minutes from creation to dept approval', null=True)),
                ('time_to_creative_approval', models.IntegerField(blank=True, help_text='Minutes from dept approval to creative approval', null=True)),
                ('time_to_assignment', models.IntegerField(blank=True, help_text='Minutes from creative approval to assignment', null=True)),
                ('time_to_start', models.IntegerField(blank=True, help_text='Minutes from assignment to start', null=True)),
                ('time_to_complete', models.IntegerField(blank=True, help_text='Minutes from start to completion', null=True)),
                ('total_cycle_time', models.IntegerField(blank=True, help_text='Total minutes from creation to confirmation', null=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.ticket')),
            ],
            options={
                'verbose_name_plural': 'Ticket analytics',
            },
        ),
    ]
