# Generated by Django 6.0 on 2025-12-23 05:10

from django.db import migrations


def cleanup_users_without_department(apps, schema_editor):
    """
    Delete users who don't have a department assigned.
    Preserves superusers and the main admin account.
    """
    User = apps.get_model('api', 'User')

    # Find users without a department (excluding superusers)
    users_without_dept = User.objects.filter(
        user_department__isnull=True,
        is_superuser=False
    )

    count = users_without_dept.count()
    if count > 0:
        print(f"\n  Deleting {count} user(s) without department assignment...")
        for user in users_without_dept:
            print(f"    - Deleting user: {user.username}")
        users_without_dept.delete()
        print(f"  Cleanup complete.\n")
    else:
        print("\n  No users without department found.\n")


def reverse_cleanup(apps, schema_editor):
    """Reverse migration does nothing - deleted users cannot be restored."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ticket_last_rollback_at_ticket_rollback_count_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_users_without_department, reverse_cleanup),
    ]
