# Generated by Django 6.0 on 2025-12-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_cleanup_users_without_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file_format',
            field=models.CharField(blank=True, choices=[('still', 'Still'), ('gif', 'Gif'), ('video_landscape', 'Video (Landscape)'), ('video_portrait', 'Video (Portrait)')], help_text='File format (only for Socmed Posting)', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(blank=True, choices=[('socmed_posting', 'Socmed Posting'), ('website_banner', 'Website Banner (H5 & WEB)'), ('photoshoot', 'Photoshoot'), ('videoshoot', 'Videoshoot'), ('live_production', 'Live Production')], help_text='Type of creative request', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='revision_count',
            field=models.IntegerField(default=0, help_text='Number of revision requests'),
        ),
        migrations.AddField(
            model_name='ticketanalytics',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When designer acknowledged/started editing', null=True),
        ),
        migrations.AddField(
            model_name='ticketanalytics',
            name='time_to_acknowledge',
            field=models.IntegerField(blank=True, help_text='Minutes from assignment to acknowledgment', null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('dept_approved', 'Department Approved'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('assigned', 'Assigned'), ('started', 'Started'), ('completed', 'Completed'), ('confirmed', 'Confirmed by Requester'), ('revision_requested', 'Revision Requested'), ('commented', 'Commented'), ('deleted', 'Deleted'), ('rollback', 'Rolled Back')], max_length=20),
        ),
    ]
