# Generated by Django 6.0 on 2025-12-26 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_ticket_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('ads', 'Ads'), ('telegram', 'Telegram')], default='general', help_text='Product category for filtering by request type', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='criteria',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], help_text='Creative type: image or video', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of creatives needed (max 1000)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='request_type',
            field=models.CharField(blank=True, choices=[('socmed_posting', 'Socmed Posting'), ('website_banner', 'Website Banner (H5 & WEB)'), ('photoshoot', 'Photoshoot'), ('videoshoot', 'Videoshoot'), ('live_production', 'Live Production'), ('ads', 'Ads'), ('telegram_channel', 'Telegram Official Channel')], help_text='Type of creative request', max_length=50),
        ),
        migrations.CreateModel(
            name='TicketProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Quantity for this product (max 1000)')),
                ('criteria', models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video')], help_text='Auto-set for Ads: VID=video, STATIC=image', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_items', to='api.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_items', to='api.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
