# Generated by Django 6.0 on 2025-12-26 10:42

from django.db import migrations


def seed_ads_telegram_products(apps, schema_editor):
    """Seed Ads and Telegram products"""
    Product = apps.get_model('api', 'Product')

    # Ads products
    ads_products = [
        'Juan365 FB VID',
        'Juan365 TIKTOK VID',
        'Juan365 FB STATIC',
        'JuanBINGO FB VID',
        'JuanBINGO TIKTOK VID',
        'DIGI ADS FB STATIC',
        'DIGI ADS FB VID',
    ]

    for name in ads_products:
        Product.objects.get_or_create(
            name=name,
            defaults={'category': 'ads', 'is_active': True}
        )

    # Telegram products
    telegram_products = [
        'Juan365 Telegram Channel',
        'JuanBingo Telegram Channel',
    ]

    for name in telegram_products:
        Product.objects.get_or_create(
            name=name,
            defaults={'category': 'telegram', 'is_active': True}
        )


def reverse_seed(apps, schema_editor):
    """Remove seeded products"""
    Product = apps.get_model('api', 'Product')
    Product.objects.filter(category__in=['ads', 'telegram']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_add_quantity_criteria_product_items'),
    ]

    operations = [
        migrations.RunPython(seed_ads_telegram_products, reverse_seed),
    ]
