# Generated by Django 6.0 on 2025-12-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_seed_ads_telegram_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='actual_end',
            field=models.DateTimeField(blank=True, help_text='Actual end time (input by assigned person on completion)', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, help_text='Scheduled end time (for videoshoot/photoshoot/live_production)', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, help_text='Scheduled start time (for videoshoot/photoshoot/live_production)', null=True),
        ),
    ]
