# Generated by Django 6.0 on 2025-12-29 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_scheduled_task_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='last_approval_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last time approval reminder was sent', null=True),
        ),
    ]
