# Generated by Django 6.0 on 2026-01-02 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_overdue_reminder_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_tickets', models.IntegerField(default=0, help_text='Total non-deleted tickets')),
                ('tickets_created', models.IntegerField(default=0, help_text='Tickets created on this date')),
                ('tickets_completed', models.IntegerField(default=0, help_text='Tickets completed on this date')),
                ('tickets_in_progress', models.IntegerField(default=0)),
                ('tickets_pending_dept', models.IntegerField(default=0, help_text='Pending department approval')),
                ('tickets_pending_creative', models.IntegerField(default=0, help_text='Pending creative approval')),
                ('tickets_approved', models.IntegerField(default=0, help_text='Not yet started')),
                ('tickets_rejected', models.IntegerField(default=0)),
                ('tickets_overdue', models.IntegerField(default=0)),
                ('urgent_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0, help_text='Total creatives produced')),
                ('video_quantity', models.IntegerField(default=0)),
                ('image_quantity', models.IntegerField(default=0)),
                ('avg_processing_seconds', models.FloatField(default=0, help_text='Avg time from start to complete')),
                ('avg_acknowledge_seconds', models.FloatField(default=0, help_text='Avg time from assign to start')),
                ('avg_video_time_seconds', models.FloatField(default=0)),
                ('avg_image_time_seconds', models.FloatField(default=0)),
                ('completion_rate', models.FloatField(default=0, help_text='Percentage of assigned tickets completed')),
                ('tickets_with_revisions', models.IntegerField(default=0)),
                ('total_revisions', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Daily statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ticket_count', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('in_progress_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.department')),
            ],
            options={
                'ordering': ['-date', 'department'],
                'unique_together': {('department', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProductSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ticket_count', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
                ('completed_count', models.IntegerField(default=0)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('in_progress_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='api.product')),
            ],
            options={
                'ordering': ['-date', 'product'],
                'unique_together': {('product', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserPerformanceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('assigned_count', models.IntegerField(default=0)),
                ('assigned_quantity', models.IntegerField(default=0, help_text='Total qty from assigned tickets')),
                ('completed_count', models.IntegerField(default=0)),
                ('output_quantity', models.IntegerField(default=0, help_text='Total qty from completed tickets')),
                ('in_progress_count', models.IntegerField(default=0)),
                ('completion_rate', models.FloatField(default=0)),
                ('avg_processing_seconds', models.FloatField(default=0)),
                ('avg_acknowledge_seconds', models.FloatField(default=0)),
                ('avg_video_time_seconds', models.FloatField(default=0)),
                ('avg_image_time_seconds', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'user'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
